#!/bin/sh

./node_modules/.bin/electron-packager ./ --platform=linux --arch=x64 --icon=sage2.icns --overwrite

cp README.lnx     SAGE2_client-linux-x64/README
cp View.lnx       SAGE2_client-linux-x64/Display0.sh
cp Fullscreen.lnx SAGE2_client-linux-x64/Fullscreen.sh

