image: node:latest

pipelines:
  branches:
    master:
    - step:
        script: # Modify the commands below to build your repository.
          - npm --version
          - npm install --only=dev
          - npm run lint
          - npm run doc
