#!/usr/bin/env python

import sys,serial

def sendCmd(cmd):
	cmd = str(cmd)
	port = "/dev/ttyS0"
	try:
		serialPort = serial.Serial(port)
	except serial.serialutil.SerialException:
		print("Unable to open serial port " + port)
		return -1

	serialPort.baudrate = 19200
	serialPort.timeout = 5 
	serialPort.write(cmd.encode())
	serialPort.flush()

	response = ""
	recvd = ""
	while(recvd != '\r'):
		recvd = str(serialPort.read())
		response += recvd
	print("planar: received " + response)
	serialPort.close()
	return response

sendCmd("op A1 display.power = 0\r")
