#!/bin/bash

pkill -9 electron


server="thor.evl.uic.edu"

export DISPLAY=:0.0
$PWD/node_modules/.bin/electron $PWD/electron.js -s http://$server -a &
sleep 1
$PWD/node_modules/.bin/electron $PWD/electron.js -d 0 -n -x 0 -y 0 --width 3072 --height 1360 -s http://$server &

export DISPLAY=:0.1
$PWD/node_modules/.bin/electron $PWD/electron.js -d 1 -n -x 0 -y 0 --width 3072 --height 1360 -s http://$server &

#$PWD/node_modules/.bin/electron $PWD/electron.js -d 0 -n -x 0 -y 0 --width 1920 --height 1080 -s http://$server &
#$PWD/node_modules/.bin/electron $PWD/electron.js -d 1 -n -x 1920 -y 0 --width 1920 --height 1080 -s http://$server &