#!/bin/bash

cd ~/sage2

tentakel pkill -9 electron

server="lyra.evl.optiputer.net"

hash=b0a0c534be83d0342e38d233643bdabb

for i in {1..18}
do
	ii=`expr $i \* 2`
	node=`printf lyra-%02d $ii`
	idx=`expr $i - 1`

	echo "================= $node: client $idx ================="

	ssh -fx $node "env DISPLAY=:0.0 $PWD/node_modules/.bin/electron $PWD/electron.js -d $idx -n -s http://$server --hash $hash -x 0 -y 0 --width 1366 --height 3072" &

done

sleep 5

for i in {1..18}
do
	ii=`expr $i \* 2`
	node=`printf lyra-%02d $ii`
	ssh -fx $node "env DISPLAY=:0.0 xdotool mousemove --sync 100 100; env DISPLAY=:0.0 xdotool mousemove --sync 10 10"

done

