#!/bin/sh

tentakel pkill -HUP chrome

server="iridium.evl.optiputer.net"
global_param="--new-window --window-size=4098,768 --kiosk --disable-popup-blocking --nfirst-run --use-gl --enable-accelerated-compositing --allow-file-access-from-files --disable-session-crashed-bubble --allow-running-insecure-content"

for i in {0..5}
do
	node=`printf orion-%02d $i`
	echo "================= $node: client $i ================="
	UDD="$HOME/.config/chrome-nfs/$node"
	param="$global_param --user-data-dir=$UDD"
	
	ssh -fx $node "env DISPLAY=:0.0 google-chrome $param 'https://$server/display.html?clientID=$i'" &
	ssh -fx $node 'sleep 3; set result=`env DISPLAY=:0.0 xdotool search --name "SAGE2: Display - Google Chrome"`; set arr=($result); echo "window: $arr[1]"; env DISPLAY=:0.0 xdotool windowmove $arr[1] 0 0' &
	ssh -fx $node 'sleep 5; env DISPLAY=:0.0 xdotool mousemove --sync 10 10; env DISPLAY=:0.0 xdotool mousemove --sync 0 0' &
done

