#!/bin/sh

killall -9 chrome

# 3072x1360
global_param="--new-window --window-size=3072,1360 --kiosk --disable-popup-blocking --no-first-run --use-gl --enable-accelerated-compositing --allow-file-access-from-files --disable-session-crashed-bubble --allow-running-insecure-content --disable-infobars  --ignore-certificate-errors"

# Launch Audio Manager
UDD=$HOME/.config/chrome-nfs/thor_audio
mkdir -p $UDD/Default
audio_param="--new-window --window-size=768,1360 --allow-file-access-from-files --allow-running-insecure-content --user-data-dir=$UDD"
env DISPLAY=:0.0 google-chrome $audio_param 'http://localhost/audioManager.html' &

sleep 1.5

# Launch Display (client 0)
UDD=$HOME/.config/chrome-nfs/thor0
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
env DISPLAY=:0.1 google-chrome $param 'http://localhost/display.html?clientID=1' &

# Move Display Client to the proper screen
sleep 1.5
export DISPLAY=:0.1

result="$(xdotool search --name 'SAGE2: Display - Google Chrome')"
arr=($result)
aLen=${#arr[@]}
lastElem=`expr $aLen - 1`
#echo "First: ${arr[0]}, Last: ${arr[$lastElem]}"

#xdotool windowmove ${arr[$lastElem]} 0 0
xdotool windowmove ${arr[0]} 0 0

xdotool mousemove --sync 10 10
xdotool mousemove --sync 0 0


# Launch Display (client 1)
UDD=$HOME/.config/chrome-nfs/thor1
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
env DISPLAY=:0.0 google-chrome $param 'http://localhost/display.html?clientID=0' &

sleep 1.5
export DISPLAY=:0.0

# Move Audio Manager to the proper screen
result="$(xdotool search --name 'Audio Manager - Google Chrome')"
arr=($result)
aLen=${#arr[@]}
lastElem=`expr $aLen - 1`
#echo "First: ${arr[0]}, Last: ${arr[$lastElem]}"

#xdotool windowmove ${arr[$lastElem]} 0 0
xdotool windowmove ${arr[0]} 0 0


# Move Display Client to the proper screen
result="$(xdotool search --name 'SAGE2: Display - Google Chrome')"
arr=($result)
aLen=${#arr[@]}
lastElem=`expr $aLen - 1`
#echo "First: ${arr[0]}, Last: ${arr[$lastElem]}"

#xdotool windowmove ${arr[$lastElem]} 0 0
xdotool windowmove ${arr[0]} 0 0

xdotool mousemove --sync 10 10
xdotool mousemove --sync 0 0

wait
