#!/bin/sh

tentakel pkill -HUP chrome

server="iridium.evl.optiputer.net"
global_param="--window-size=4098,768 --kiosk --disable-popup-blocking --nfirst-run --use-gl --enable-accelerated-compositing --allow-file-access-from-files"

for i in {0..5}
do
	node=`printf orion-%02d $i`
	echo "================= $node: client $i ================="
	UDD="$HOME/.config/chrome-nfs/$node"
	param="$global_param --user-data-dir=$UDD"
	
	ssh -fx $node "env DISPLAY=:0.0 google-chrome $param 'https://$server?clientID=$i'" &
	ssh -fx $node "sleep 2; env DISPLAY=:0.0 result=\"$(xdotool search --name 'SAGE2: Display - Google Chrome')\"; arr=($result); echo \"window: ${arr[0]}\"; env DISPLAY=:0.0 xdotool windowmove ${arr[0]} 0 0" &
	ssh -fx $node "sleep 5; env DISPLAY=:0.0 xdotool mousemove --sync 10 10; env DISPLAY=:0.0 xdotool mousemove --sync 0 0" &
done
