#!/bin/sh

pkill -HUP chrome

server=preeka.evl.uic.edu


# Launch Audio Manager
UDD=$HOME/.config/chrome-nfs/preeka_audio
mkdir -p $UDD/Default
audio_param="--window-size=768,1360 --allow-running-insecure-content --allow-file-access-from-files"
env DISPLAY=:0.0 google-chrome $audio_param "https://$server/audioManager.html" &

sleep 2

global_param="--disable-webaudio --mute-audio --kiosk --window-size=2560,1600 --disable-popup-blocking --nfirst-run --use-gl --enable-accelerated-compositing --allow-file-access-from-files --incognito --allow-running-insecure-content"

UDD="$HOME/.config/chrome-nfs/preeka0"
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
env DISPLAY=:0.1 google-chrome $param "https://$server/display.html?clientID=2" &

UDD="$HOME/.config/chrome-nfs/preeka1"
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
env DISPLAY=:0.2 google-chrome $param "https://$server/display.html?clientID=3" &

UDD="$HOME/.config/chrome-nfs/preeka2"
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
env DISPLAY=:0.3 google-chrome $param "https://$server/display.html?clientID=4" &

UDD="$HOME/.config/chrome-nfs/preeka3"
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
env DISPLAY=:0.4 google-chrome $param "https://$server/display.html?clientID=0" &

UDD="$HOME/.config/chrome-nfs/preeka4"
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
env DISPLAY=:0.0 google-chrome $param "https://$server/display.html?clientID=1" &

sleep 3
export DISPLAY=:0.0
xdotool mousemove --sync 10 10
xdotool mousemove --sync 0 0

