#!/bin/sh

killall -HUP chrome

global_param="--new-window --window-size=1920,1080  --disable-popup-blocking --no-first-run --use-gl --enable-accelerated-compositing --allow-file-access-from-files --disable-session-crashed-bubble --allow-running-insecure-content --disable-infobars  --ignore-certificate-errors --no-default-browser-check"

# Launch Audio Manager
UDD=$HOME/.config/chrome-nfs/traoumad_audio
/bin/rm -fr $UDD
mkdir -p $UDD/Default
audio_param="--disable-infobars --no-default-browser-check --ignore-certificate-errors --window-size=768,580 --allow-file-access-from-files --user-data-dir=$UDD"
env DISPLAY=:0.0 google-chrome $audio_param 'https://traoumad.evl.uic.edu/audioManager.html' &

sleep 1

# Launch Display (client 0)
UDD=$HOME/.config/chrome-nfs/traoumad_0
/bin/rm -fr $UDD
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
env DISPLAY=:0.0 google-chrome $param 'https://traoumad.evl.uic.edu/display.html?clientID=0' &

sleep 1

# Launch Display (client 1)
UDD=$HOME/.config/chrome-nfs/traoumad_1
/bin/rm -fr $UDD
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
env DISPLAY=:0.0 google-chrome $param 'https://traoumad.evl.uic.edu/display.html?clientID=1' &


sleep 5
export DISPLAY=:0.0

# Move Audio Manager to the proper screen
result="$(xdotool search --name 'SAGE2: Audio Manager')"
arr=($result)
aLen=${#arr[@]}
lastElem=`expr $aLen - 1`

xdotool windowmove ${arr[0]} 0 0


# Move Display Client to the proper screen
result="$(xdotool search --name 'SAGE2: Display')"
arr=($result)
aLen=${#arr[@]}
lastElem=`expr $aLen - 1`

xdotool windowmove ${arr[$lastElem]} 1920 0
xdotool windowmove ${arr[0]} 0 0

#xdotool key --window ${arr[$lastElem]} F11
#xdotool key --window ${arr[0]} F11

xdotool mousemove --sync 10 10
xdotool mousemove --sync 0 0

