#!/bin/sh

# SAGE2 is available for use under the SAGE2 Software License
# 
# University of Illinois at Chicago's Electronic Visualization Laboratory (EVL)
# and University of Hawai'i at Manoa's Laboratory for Advanced Visualization and
# Applications (LAVA)
# 
# See full text, terms and conditions in the LICENSE.txt included file
#
# Copyright (c) 2014

#
# to generate a list of certificates, add the server name in the list below
# and run ./GO-linux
#
# If you have a real certificate for your server, place it in the folder
# No need to generate one:
#      127.0.0.1.crt
#      127.0.0.1.key
# Wildcard certificates:
#      _.evl.uic.edu.crt
#      _.evl.uic.edu.key

sudo apt-get update 
sudo apt-get -y install libnss3-tools openssl

# Reset the key database
rm -fr /sage2/.pki/nssdb
mkdir -p  /sage2/.pki/nssdb
echo "" > /tmp/pass
echo "" >> /tmp/pass
certutil -f /tmp/pass -d sql:/sage2/.pki/nssdb -N
/bin/rm -f /tmp/pass
cd /sage2/keys

# Generate new keys
servers="$1 127.0.0.1 0.0.0.0 localhost"

for f in `echo $servers`
do
	./init_webserver_docker.sh $f
done

