#!/bin/sh

# SAGE2 is available for use under the SAGE2 Software License
# 
# University of Illinois at Chicago's Electronic Visualization Laboratory (EVL)
# and University of Hawai'i at Manoa's Laboratory for Advanced Visualization and
# Applications (LAVA)
# 
# See full text, terms and conditions in the LICENSE.txt included file
#
# Copyright (c) 2014

#
# to generate a list of certificates, add the server name in the list below
# and run ./GO-linux
#
# If you have a real certificate for your server, place it in the folder
# No need to generate one:
#      127.0.0.1.crt
#      127.0.0.1.key
# Wildcard certificates:
#      _.evl.uic.edu.crt
#      _.evl.uic.edu.key


servers="$HOSTNAME localhost 127.0.0.1"

for f in `echo $servers`
do
	./init_webserver.sh $f
done
