#!/bin/sh

# SAGE2 is available for use under the following license, commonly known
#          as the 3-clause (or "modified") BSD license:
#
# Copyright (c) 2014, Electronic Visualization Laboratory,
#                     University of Illinois at Chicago
# All rights reserved.
#
# http://opensource.org/licenses/BSD-3-Clause
# See included LICENSE.txt file

#
# to generate a list of certificates, add the server name in the list below
# and run ./GO-linux
#
# If you have a real certificate for your server, place it in the folder
# No need to generate one:
#      127.0.0.1.crt
#      127.0.0.1.key
# Wildcard certificates:
#      _.evl.uic.edu.crt
#      _.evl.uic.edu.key


servers="$HOSTNAME localhost 127.0.0.1"

for f in `echo $servers`
do
	./init_webserver.sh $f
done
