#!/bin/sh

#
# to generate a list of certificates, add the server name in the list below
# and run ./GO-mac
#
# If you have a real certificate for your server, place it in the folder
# No need to generate one:
#      127.0.0.1.crt
#      127.0.0.1.key
# Wildcard certificates:
#      _.evl.uic.edu.crt
#      _.evl.uic.edu.key


servers="$HOSTNAME localhost 127.0.0.1"

for f in `echo $servers`
do
	./init_webserver.cmd $f
done

/usr/bin/security add-trusted-cert -d -r trustRoot localhost-server.crt

